### PR TITLE
added another thread for logging

### PR DESCRIPTION
**Pull request by huuck**
This should solve the I/O wait for logging more intensive attacks being sent.

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
@huuck Ready for testing? Just let me know.

**Comment by huuck** [comment]
I'll take a look tonight and keep you posted.

**Comment by huuck** [comment]
gonna merge it into main, the tests all show behavior similar to the baseline

**Comment by t3chn0m4g3** [comment]
Great. Thank you!

**Pull request merged**
