### PR TITLE
added python3.6 support

### PR DESCRIPTION
**Pull request by RayofLightz**
Ported the code base to python3.6 because 2.7 hits EOL soon. I tested the two supported commands `adb shell` and `adb push` and the code worked. I had to change the name of some imported modules and had to convert certain strings to bytes objects.

### CODE REVIEW

**Comment by huuck** [comment]
Hi!

It's crashing through certain adb push flows:
image

Please test it with different file types (<64 bytes, >4MB and so on) and different network conditions, not only localhost stuff.

Let me know if you can/can't fix it, as the rest looks good.

Kindest regards,
Gabriel

**Comment by RayofLightz** [comment]
Okay, will get to work on fixing it :)

**Comment by RayofLightz** [comment]
I just fixed the large file bug that was occurring. I had to add a check on `recv_binary_chunk` to stop an infinite loop that occurred. The program would hang and kept saying that it was receiving a chunk of 0 bytes

**Comment by huuck** [comment]
Only a few minor bugs which I'll fix. Going for the merge.

**Pull request merged**
